- src/main/java/io/th0rgal/oraxen/pack/ResourcePack.java
- src/main/java/io/th0rgal/oraxen/settings/Pack.java
- src/main/java/io/th0rgal/oraxen/settings/ResourcesManager.java
- src/main/java/io/th0rgal/oraxen/settings/Server.java
- src/main/java/io/th0rgal/oraxen/utils/ZipUtils.java
- Refactor ResourcePack and ResourcesManager classes
- Fix typo in Server class
- Improve Pack enum performance
> Some refactors, fix typo, improve performance

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- src/main/java/io/th0rgal/oraxen/commands/CommandHandler.java
- src/main/java/io/th0rgal/oraxen/commands/subcommands/Debug.java
- src/main/java/io/th0rgal/oraxen/items/ItemParser.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/block/BlockMechanicsListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/commands/CommandsMechanic.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/commands/CommandsMechanicFactory.java
- src/main/java/io/th0rgal/oraxen/pack/PredicatesGenerator.java
- src/main/java/io/th0rgal/oraxen/pack/ResourcePack.java
- src/main/java/io/th0rgal/oraxen/recipes/RecipesManager.java
- src/main/java/io/th0rgal/oraxen/recipes/loaders/ShapelessLoader.java
- Refactor RecipesManager
- Refactor a bit PredicatesGenerator, CommandHandler, BlockMechanicsListener and ResourcePack
- Remove unused imports
- Update gradle wrapper from 5.2.1 to 5.6.3
- Modify build.gradle in order to add some build infos to MANIFEST.MF
> Some refactors, update gradle wrapper, improve build.gradle

- src/main/java/io/th0rgal/oraxen/commands/subcommands/Give.java
- src/main/java/io/th0rgal/oraxen/items/ItemBuilder.java
- src/main/java/io/th0rgal/oraxen/items/OraxenItems.java
- src/main/java/io/th0rgal/oraxen/mechanics/MechanicsManager.java
- src/main/java/io/th0rgal/oraxen/pack/upload/UploadManager.java
- src/main/java/io/th0rgal/oraxen/pack/upload/hosts/TransferDotSh.java
- src/main/java/io/th0rgal/oraxen/recipes/RecipesManager.java
- src/main/java/io/th0rgal/oraxen/utils/drops/Loot.java
- ✨ Indicates when connection to host provider is impossible
- ♻️ Remove some else
- ♻️ Add variables
- ♻️ Add a private method
- 🔥 Remove already done todos
- 🚨 Add some private modifiers
- 🚨 Add a break
- 🎨 Move a field declaration at the top of the class
- 🎨 Remove some useless this
> Bug prevention, a bit of refactor, remove some linter warns, etc.

- src/main/java/io/th0rgal/oraxen/items/ItemBuilder.java
> 🔀 Lgtm fix

- src/main/java/io/th0rgal/oraxen/mechanics/provided/commands/CommandsMechanicListener.java
- src/main/java/io/th0rgal/oraxen/pack/dispatch/PackSender.java
- src/main/java/io/th0rgal/oraxen/pack/receive/PackReceiver.java
- src/main/java/io/th0rgal/oraxen/pack/upload/UploadManager.java
- src/main/java/io/th0rgal/oraxen/settings/Pack.java
- src/main/java/io/th0rgal/oraxen/utils/KeyGenerator.java
- src/main/java/io/th0rgal/oraxen/utils/message/BossbarManager.java
- src/main/java/io/th0rgal/oraxen/utils/message/BossbarMessager.java
- src/main/java/io/th0rgal/oraxen/utils/message/ComponentMessage.java
- src/main/java/io/th0rgal/oraxen/utils/message/Message.java
- src/main/java/io/th0rgal/oraxen/utils/message/MessageAction.java
- src/main/java/io/th0rgal/oraxen/utils/message/MessageTimer.java
- src/main/resources/settings.yml
Added possibility to run commands / do message actions if the texture pack was downloaded successfully / the download failed or download was denied.
(Currently untested xD)
And fixed a small issue that caused the player commands to never run with the command mechanic
> Added Pack receiving actions

- src/main/java/io/th0rgal/oraxen/OraxenPlugin.java
- src/main/java/io/th0rgal/oraxen/commands/brigadier/BrigadierManager.java
- src/main/java/io/th0rgal/oraxen/commands/subcommands/Recipes.java
- src/main/java/io/th0rgal/oraxen/recipes/RecipesManager.java
- src/main/java/io/th0rgal/oraxen/recipes/builders/FurnaceBuilder.java
- src/main/java/io/th0rgal/oraxen/recipes/builders/RecipeBuilder.java
- src/main/java/io/th0rgal/oraxen/recipes/listeners/RecipesBuilderEvents.java
- src/main/java/io/th0rgal/oraxen/recipes/loaders/FurnaceLoader.java
- src/main/java/io/th0rgal/oraxen/recipes/loaders/ShapelessLoader.java
- src/main/java/io/th0rgal/oraxen/utils/armorequipevent/ArmorType.java
- src/main/java/io/th0rgal/oraxen/utils/signinput/SignMenuFactory.java
- src/main/resources/recipes/furnace.yml
Add support for Shapeless and Furnace Recipes, add Furnace Recipe Builder.
> Add support for Shapeless and Furnace Recipes, add Furnace Recipe Builder.

- src/main/java/io/th0rgal/oraxen/recipes/builders/RecipeBuilder.java
- src/main/java/io/th0rgal/oraxen/recipes/builders/ShapelessBuilder.java
Fix Shapeless Recipe Builder and unable to change Recipe Builder
> Fix Shapeless Recipe Builder and unable to change Recipe Builder

- src/main/java/io/th0rgal/oraxen/mechanics/MechanicsManager.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/harvesting/HarvestingMechanic.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/harvesting/HarvestingMechanicFactory.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/harvesting/HarvestingMechanicManager.java
- src/main/resources/items/tools.yml
- src/main/resources/mechanics.yml
> Add Harvesting Mechanic

- src/main/java/io/th0rgal/oraxen/mechanics/MechanicsManager.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/energyblast/EnergyBlastMechanic.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/energyblast/EnergyBlastMechanicFactory.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/energyblast/EnergyBlastMechanicManager.java
- src/main/java/io/th0rgal/oraxen/utils/VectorUtils.java
- src/main/resources/items/mystical.yml
- src/main/resources/mechanics.yml
> Add Energy Blast Mechanic

- build.gradle
- src/main/java/io/th0rgal/oraxen/commands/subcommands/Debug.java
- src/main/java/io/th0rgal/oraxen/items/ItemBuilder.java
- src/main/java/io/th0rgal/oraxen/utils/reflection/ItemTools.java
- src/main/java/io/th0rgal/oraxen/utils/reflection/NbtTools.java
- src/main/java/io/th0rgal/oraxen/utils/reflection/ReflectionProvider.java
- src/main/java/io/th0rgal/oraxen/utils/reflection/Reflections.java
- src/main/java/io/th0rgal/oraxen/utils/reflection/version/MinecraftVersion.java
- src/main/java/io/th0rgal/oraxen/utils/reflection/version/ServerVersion.java
Added Reflection classes
Added custom nbt tags to ItemBuilder
Added override nbt tags to ItemBuilder
> Added reflections and more Item Nbt

- src/main/java/io/th0rgal/oraxen/OraxenPlugin.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/bigmining/BigMiningMechanicListener.java
- src/main/resources/plugin.yml
Attention WorldGuard adore tout mettre en deny même s'il n'y a rien, obligé au personne de mettre allow dans les flags de leur regions sur le block-break
> Ajout WorldGuard sur Hammer et nouvelle permission oraxen.worldguard.bypass

- src/main/java/io/th0rgal/oraxen/command/permission/IPermission.java
A branch for just 18-19 chars additions (just adding a replace lol)
> Fixed a permission bug to not format the permission enum correctly

- src/main/java/io/th0rgal/oraxen/language/Translations.java
> Fixed black magic

- build.gradle
- src/main/java/io/th0rgal/oraxen/mechanics/MechanicsManager.java
- src/main/java/io/th0rgal/oraxen/pack/generation/PredicatesGenerator.java
- src/main/java/io/th0rgal/oraxen/recipes/RecipesManager.java
- src/main/java/io/th0rgal/oraxen/settings/ConfigUpdater.java
- src/main/java/io/th0rgal/oraxen/settings/ConfigsManager.java
- src/main/java/io/th0rgal/oraxen/settings/Pack.java
- src/main/java/io/th0rgal/oraxen/settings/ResourcesManager.java
- src/main/java/io/th0rgal/oraxen/settings/Update.java
- src/main/java/io/th0rgal/oraxen/settings/UpdateInfo.java
- src/main/java/io/th0rgal/oraxen/settings/update/ExampleUpdate.java
- src/main/java/io/th0rgal/oraxen/utils/Utils.java
**Added update feature for configs**
(through pink magic)
> This time I got pink magic!

- build.gradle
- src/main/java/io/th0rgal/oraxen/OraxenPlugin.java
- src/main/java/io/th0rgal/oraxen/command/condition/CommandCondition.java
- src/main/java/io/th0rgal/oraxen/command/condition/Conditions.java
- src/main/java/io/th0rgal/oraxen/command/condition/ICondition.java
- src/main/java/io/th0rgal/oraxen/command/condition/MixedCommandCondition.java
- src/main/java/io/th0rgal/oraxen/command/condition/MixedCondition.java
- src/main/java/io/th0rgal/oraxen/event/config/OraxenConfigEvent.java
- src/main/java/io/th0rgal/oraxen/mechanics/MechanicsManager.java
- src/main/java/io/th0rgal/oraxen/pack/generation/ResourcePack.java
- src/main/java/io/th0rgal/oraxen/recipes/RecipesManager.java
- src/main/java/io/th0rgal/oraxen/settings/ConfigUpdater.java
- src/main/java/io/th0rgal/oraxen/settings/ConfigsManager.java
- src/main/java/io/th0rgal/oraxen/settings/ResourcesManager.java
- src/main/java/io/th0rgal/oraxen/settings/Update.java
- src/main/java/io/th0rgal/oraxen/settings/UpdateInfo.java
- src/main/java/io/th0rgal/oraxen/settings/update/ExampleUpdate.java
- src/main/java/io/th0rgal/oraxen/utils/ReflectionUtils.java
- src/main/java/io/th0rgal/oraxen/utils/Utils.java
- src/main/java/io/th0rgal/oraxen/utils/ZipUtils.java
- src/main/java/io/th0rgal/oraxen/utils/general/Container.java
- src/main/java/io/th0rgal/oraxen/utils/general/ValueConsumer.java
- src/main/java/io/th0rgal/oraxen/utils/general/ValueProvider.java
We love magic but I had to remove some and replace it with logic :c
> Fixed ConfigUpdater and added Javadoc / Sources generation

- src/main/resources/plugin.yml
Ce n'est pas testé !!! 
fix issue https://github.com/oraxen/Oraxen/issues/85
> Charge avant que le plugin cratereloaded se charge

- src/main/java/io/th0rgal/oraxen/mechanics/provided/lifeleech/LifeLeechMechanicListener.java
Fixe de ce bug : 
https://hastebin.com/wudacaxazi.sql
> Fix d'un bug du cast en 1.16

- src/main/java/io/th0rgal/oraxen/mechanics/provided/smelting/SmeltingMechanicListener.java
Java 11 is LTS but java 8 is used because never update by owner server
> Return to Java 8

- build.gradle
- src/main/java/io/th0rgal/oraxen/mechanics/MechanicsManager.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/durability/DurabilityMechanicManager.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/invisibleitemframe/InvisibleItemFrameFactory.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/invisibleitemframe/InvisibleItemFrameListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/invisibleitemframe/InvisibleItemFrameMechanic.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/potioneffects/PotionEffectsMechanic.java
- src/main/resources/items/items.yml
- src/main/resources/mechanics.yml
Update module for support java 15+ (only compile)
Remove duplication WorldGuard
Update latest version module
Add 1.16 because add Mechanics Invisible Item Frame !
> More Update !

- build.gradle
- src/main/java/io/th0rgal/oraxen/OraxenPlugin.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/potioneffects/PotionEffectsMechanicListener.java
- src/main/java/io/th0rgal/oraxen/utils/Metrics/Metrics.java
Its not a PR with more update, but better stats on bstats for your plugin with online mode because dont support bungeecord online mode.
Add : 
Player has an issue if Oraxen charge first and not protocollib so class is not found
> Add better support Metrics and Online Mode

- build.gradle
- src/main/java/io/th0rgal/oraxen/mechanics/provided/block/BlockMechanicListener.java
- src/main/resources/plugin.yml
Bad condition with block physics (crash server)
Remove loadbedore patch plugin.yml because broken with other plugins
> Important BUG ! 

- build.gradle
- src/main/java/io/th0rgal/oraxen/mechanics/provided/block/BlockMechanic.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/block/BlockMechanicFactory.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/block/BlockMechanicListener.java
- src/main/resources/items/blocks.yml
Rollback PR https://github.com/oraxen/Oraxen/pull/89
Fix bug PR https://github.com/oraxen/Oraxen/pull/96
> RollBack PR more mushroom

- src/main/java/io/th0rgal/oraxen/settings/update/ToolTypesUpdate.java
> Fix ToolTypeUpdate

- README.md
- src/main/java/io/th0rgal/oraxen/utils/Utils.java
I got a FileNotFoundException on first startup with no configs. This fixes them. +a small typo fix (I assume)
> 1st startup error fix

- src/main/java/io/th0rgal/oraxen/command/argument/ArgumentHelper.java
A better solution would require an update to the command library itself.
> Fixed #111

- src/main/java/io/th0rgal/oraxen/command/commands/Reload.java
- src/main/java/io/th0rgal/oraxen/pack/upload/UploadManager.java
- src/main/java/io/th0rgal/oraxen/pack/upload/hosts/HostingProvider.java
- src/main/java/io/th0rgal/oraxen/pack/upload/hosts/Polymath.java
- src/main/java/io/th0rgal/oraxen/pack/upload/hosts/Sh.java
Improved pack upload by adding a more specific message if something wents wrong on upload
Improved the "/oraxen reload pack" command by sending the resourcepack on successful upload to all online players
> Improved pack upload

- src/main/java/io/th0rgal/oraxen/mechanics/MechanicsManager.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/consumable/ConsumableMechanic.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/consumable/ConsumableMechanicFactory.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/consumable/ConsumableMechanicListener.java
- src/main/resources/mechanics.yml
Right clicked item is used: itemstack quantity - 1
> Add consumable mechanic

- src/main/java/io/th0rgal/oraxen/mechanics/provided/consumable/ConsumableMechanicListener.java
Fix consumable mechanic by updating proper item slot when consumable item is in off hand
> Fix consumable mechanic issue

- src/main/java/io/th0rgal/oraxen/mechanics/provided/furniture/FurnitureListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/furniture/FurnitureMechanic.java
- src/main/resources/items/blocks.yml
This pr adds an optional seat option to the furniture mechanic
> introduce seats

- src/main/java/io/th0rgal/oraxen/OraxenPlugin.java
- src/main/java/io/th0rgal/oraxen/commands/CommandsManager.java
- src/main/java/io/th0rgal/oraxen/commands/RecipesCommand.java
- src/main/java/io/th0rgal/oraxen/commands/ReloadCommand.java
- src/main/java/io/th0rgal/oraxen/commands/RepairCommand.java
- src/main/java/io/th0rgal/oraxen/compatibilities/CompatibilitiesManager.java
- src/main/java/io/th0rgal/oraxen/compatibilities/provided/mythicmobs/MythicMobsCompatibility.java
- src/main/java/io/th0rgal/oraxen/config/Message.java
- src/main/java/io/th0rgal/oraxen/config/Settings.java
- src/main/java/io/th0rgal/oraxen/items/ItemParser.java
- src/main/java/io/th0rgal/oraxen/items/ItemUpdater.java
- src/main/java/io/th0rgal/oraxen/items/OraxenMeta.java
- src/main/java/io/th0rgal/oraxen/pack/dispatch/AdvancedPackSender.java
- src/main/java/io/th0rgal/oraxen/pack/dispatch/BukkitPackSender.java
- src/main/resources/languages/english.yml
- src/main/resources/settings.yml
Item update command:
/o update <targets> all/hand
Also fix commands can't select multiple players
> Introduce Item updating and fix command arguments

- src/main/java/io/th0rgal/oraxen/utils/breaker/BreakerSystem.java
Fixed bug described in #219
~aerulion
> fix sending block break multiple times to same player

- src/main/java/io/th0rgal/oraxen/mechanics/provided/farming/bottledexp/BottledExpMechanicListener.java
pretty annoying for pickaxes (maybe you can make it configurable, idk)
> Dont make bottles, when mining a block

- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/furniture/FurnitureListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/furniture/FurnitureMechanic.java
**Hey there 👋**
My pull request offers the possibility to find out when a furniture could not be placed (lack of space).
It is tested and works perfectly.
See here for more information: https://github.com/oraxen/oraxen/issues/272
> Fix BlockPlaceEvent of furnitures is not cancelled (#272)

- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/furniture/FurnitureListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/furniture/FurnitureMechanic.java
https://user-images.githubusercontent.com/32105478/161404899-236093fd-1b9c-475f-b6f7-d04288ff75fd.mp4
Reported by @lucian929
> fix for when clicking with a furniture item on a furniture block that has click actions

- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/furniture/FurnitureListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/furniture/FurnitureMechanic.java
Reverts oraxen/oraxen#306
While testing, @lucian929 found out that the fix isn't complete, and I forgot to put the PR on draft 😒 I apologize about that
> Revert "fix for when clicking with a furniture item on a furniture block that has click actions"

- build.gradle
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/furniture/FurnitureListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/furniture/FurnitureMechanic.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/furniture/evolution/EvolutionTask.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/stringblock/StringBlockMechanicFactory.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/stringblock/StringBlockMechanicListener.java
This PR mainly consists of bug fixes for visual and some bigger bugs.
Fixes issue with crops growing past their final stage, and thus breaking.
This is imported from #316 as that PR wont be fully ready to merge for abit longer.
Also fixes client side visual bug with stringblocks, where the client predicts a blockchange that doesnt happen serverside.
Probably a more optimal way to check this and radius probably does not need to be this big but
https://user-images.githubusercontent.com/62521371/165134130-f447ba46-125a-4c86-81a6-ae7a6cc7636b.mp4
Fixes bug where stringblock float if breaking block below them
https://user-images.githubusercontent.com/62521371/165140000-c34cf56a-9e8d-47dc-bcee-b33aa69751a4.mp4
> Various bug fixes

- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/noteblock/NoteBlockMechanic.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/noteblock/NoteBlockMechanicFactory.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/noteblock/logstrip/LogStripListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/noteblock/logstrip/LogStripping.java
Adds a "log stripping" mechanic to noteblocks. Additional feature nice for making custom logs
https://user-images.githubusercontent.com/62521371/166521978-291bf9bd-ff37-45dc-ad6b-c568df9254bf.mp4
> add log stripping mechanic for noteblocks

- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/furniture/FurnitureListener.java
Little thing, but I think it's a good way to improve furniture interactions so they look more realistic.
I did this in about 30 seconds so please let me know if there are any issues, so far it's working fine for me
> Play animation on furniture click

- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/furniture/evolution/EvolutionTask.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/noteblock/farmblock/FarmBlockTask.java
Fixes oopsie with casting moistfarmblock to moistfarmblock and some additional checks
> fix some nullpointers and casting errors

- build.gradle
> Bump version number

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/suggestion.yml
- build.gradle
Made some super nice issue templates so we can better keep track of issues.
> Issue Templates

- src/main/java/io/th0rgal/oraxen/OraxenPlugin.java
Ceci fix tous les nullpointer sur les compatibilités
> Fix Compatibilites

- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/noteblock/NoteBlockMechanicListener.java
Was meant to simply fix water-physics on CB's but fixed abit more
Fixes placing liquid/snow via buckets on CB's
Fixes picking up liquid/snow from CB's
Fixes liquid-flowing when placed via buckets on CB's
Fixes Entity Buckets like axolotls not spawning when used
Fixes buckets being removed when placed on CB's
Fixes CB's dropping even when in Creative Mode
Fixes sound-related issues with placing/breaking on CB's
Fixes placing chests/interactables on CB's (Unsure why this was there to begin with?)
Fixed placing CB's on CB's
Fixed placing light blocks on CB's
https://user-images.githubusercontent.com/62521371/168052057-082b53ec-2300-4199-ab2f-9e54de7c2524.mp4
https://user-images.githubusercontent.com/62521371/168052087-e3a2bbe7-3562-4c13-9143-95e261d3d382.mp4 …
> More CustomBlock fixes

- src/main/resources/items/plants.yml
Seems this has been the issue for the longest time with crops dying
> Fix issue with default configs

- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/furniture/FurnitureListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/furniture/FurnitureMechanic.java
> fix furniture hitbox bug

- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/stringblock/StringBlockMechanicListener.java
This does rely on a PaperSpigot event, much like the EntityInsideBlockEvent used to cancel those updates.
Not sure what the limit is for not sticking to Spigot so ill leave this here
https://streamable.com/3015x5
(file too big for showing here sadly)
> fix string dropping incorrectly from water

- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/furniture/FurnitureListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/furniture/FurnitureMechanic.java
Cancels placing when interacting with clickAction stuff (unless player sneakin)
_nvm all the particle bs from stone, client side mod i forgot to tweak_
https://streamable.com/dktlge
> fix clickAction and block interactions

- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/noteblock/NoteBlockMechanicListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/stringblock/StringBlockMechanicListener.java
- src/main/java/io/th0rgal/oraxen/utils/BlockHelpers.java
- src/main/java/io/th0rgal/oraxen/utils/Utils.java
- src/main/java/io/th0rgal/oraxen/utils/breaker/BreakerSystem.java
- src/main/java/io/th0rgal/oraxen/utils/drops/Drop.java
https://user-images.githubusercontent.com/62521371/169089390-2f299a1b-46e6-4f28-87ad-347d124b4c62.mp4
> fix placing/breaking next to tripwire updating it

- src/main/java/io/th0rgal/oraxen/utils/BlockHelpers.java
- src/main/java/io/th0rgal/oraxen/utils/drops/Drop.java
forgot some debug stuff for 1.135.5
> remove debug stuff

- src/main/java/io/th0rgal/oraxen/items/OraxenItems.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/block/BlockMechanicListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/furniture/FurnitureListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/noteblock/NoteBlockMechanicListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/stringblock/StringBlockMechanicListener.java
- src/main/java/io/th0rgal/oraxen/utils/BlockHelpers.java
- src/main/java/io/th0rgal/oraxen/utils/Utils.java
Fixes issues with placed containers not copying inventory (shulkers and chests with nbt)
Spawns falling blocks when placed on blocks
> even more fixes

- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/noteblock/NoteBlockMechanicListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/stringblock/StringBlockMechanicListener.java
- src/main/java/io/th0rgal/oraxen/utils/BlockHelpers.java
Fixes all issues with placing non custom blocks on non custom blocks (forgot to invert a check seemingly)
Actually fixes banners, anvils, saplings and so on placing on custom blocks
Also some cleanup
> Block rotation fixes

- src/main/java/io/th0rgal/oraxen/OraxenPlugin.java
- src/main/java/io/th0rgal/oraxen/commands/CommandsManager.java
- src/main/java/io/th0rgal/oraxen/commands/PrintFontCommand.java
- src/main/java/io/th0rgal/oraxen/commands/PrintGlyphCommand.java
This is an ESSENTIAL feature to ease the use of emoji, guis, and custom fonts.
i'll also create the documentation if this pull request will be accepted
> Very useful feature to manage custom fonts

- src/main/resources/languages/czech.yml
I have added czech translations
> Created czech.yml

- src/main/java/io/th0rgal/oraxen/OraxenPlugin.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/furniture/FurnitureMechanic.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/stringblock/sapling/SaplingTask.java
seems letting cbd handle it makes barriers unbreakable
so switch to manually removing where set
> Fix furniture being unbreakable

- src/main/java/io/th0rgal/oraxen/commands/CommandsManager.java
- src/main/java/io/th0rgal/oraxen/commands/ItemInfoCommand.java
This command is basically used for retrieving customModelData id and other item information in-game.
> Very useful command /oraxen iteminfo

- src/main/resources/languages/pt-BR.yml
This pull request adds Brazilian portuguese translation to oraxen.
> Add Brazilian portuguese translation

- build.gradle
- src/main/java/io/th0rgal/oraxen/compatibilities/provided/mythiccrucible/WrappedCrucibleItem.java
- src/main/java/io/th0rgal/oraxen/config/ConfigsManager.java
- src/main/java/io/th0rgal/oraxen/items/ItemBuilder.java
- src/main/java/io/th0rgal/oraxen/items/ItemParser.java
- src/main/resources/plugin.yml
Closes #371 
```yml
example_crucible:
displayname: "<gradient:#59A7EA:#F1D2FF>Test"
crucible:
id: crucible_item```
> mythiccrucible compatibility

- src/main/java/io/th0rgal/oraxen/mechanics/MechanicsManager.java
This makes the commands mechanic work again.
The docs should be updated since they say the cooldown is in seconds while in reality it's in milliseconds.
> Added commands to mechanics manager

- src/main/java/io/th0rgal/oraxen/sound/CustomSound.java
- src/main/java/io/th0rgal/oraxen/sound/SoundManager.java
Added play/stop in CustomSound
SoundCategory enum
Getters
> CustomSound improvements

- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/block/BlockMechanicListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/furniture/FurnitureListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/noteblock/NoteBlockMechanicListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/stringblock/StringBlockMechanicListener.java
> fix adventure mode not being respected

- src/main/java/io/th0rgal/oraxen/mechanics/provided/misc/custom/fields/CustomEventType.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/misc/custom/listeners/DropListener.java
> fix drop and add itembreak clickactions

- src/main/java/io/th0rgal/oraxen/sound/CustomSound.java
- src/main/java/io/th0rgal/oraxen/sound/SoundManager.java
Fix CustomSound.getSounds, my mistake
> Fix my mistake

- src/main/java/io/th0rgal/oraxen/utils/breaker/BreakerSystem.java
Fix for #475 . Was returning minecraft:SoundKey vs SoundKey like other sounds
> Bedrock Pick Fix

- src/main/java/io/th0rgal/oraxen/config/Settings.java
- src/main/java/io/th0rgal/oraxen/pack/generation/ResourcePack.java
- src/main/java/io/th0rgal/oraxen/utils/CustomArmorsTextures.java
- src/main/resources/settings.yml
This generates the files inside `Oraxen/pack/optifine` just fine, but it doesnt include it in the final zip file.
Not entirely sure atm how that works but guessing its to do with VirtualFile
> Generate shader armor automatically

- src/main/java/io/th0rgal/oraxen/utils/CustomArmorsTextures.java
not fully verified finished but rushed together last night and fixed some errors
> properly check filepath for custom armor

- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/block/BlockMechanicListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/furniture/FurnitureListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/noteblock/NoteBlockMechanicListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/stringblock/StringBlockMechanicListener.java
- src/main/java/io/th0rgal/oraxen/utils/BlockHelpers.java
- src/main/java/io/th0rgal/oraxen/utils/breaker/BreakerSystem.java
Closes #494 , Closes #434, Closes #479, Closes #454
> Bugfixes etc

- src/main/java/io/th0rgal/oraxen/commands/PrintGlyphCommand.java
> Include new glyphs after reload in printglyph command

- src/main/java/io/th0rgal/oraxen/config/ConfigsManager.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/block/BlockSoundListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/furniture/FurnitureSoundListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/noteblock/NoteBlockSoundListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/noteblock/logstrip/LogStripListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/stringblock/StringBlockSoundListener.java
- src/main/java/io/th0rgal/oraxen/utils/BlockHelpers.java
- src/main/java/io/th0rgal/oraxen/utils/blocksounds/BlockSounds.java
- src/main/java/io/th0rgal/oraxen/utils/breaker/BreakerSystem.java
> More minor stuff

- src/main/java/io/th0rgal/oraxen/items/ItemBuilder.java
- src/main/java/io/th0rgal/oraxen/items/ItemParser.java
> add unstackable property

- src/main/java/io/th0rgal/oraxen/hud/HudManager.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/block/BlockMechanicListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/furniture/FurnitureListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/furniture/FurnitureMechanic.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/furniture/FurnitureSoundListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/noteblock/NoteBlockMechanicListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/stringblock/StringBlockMechanicListener.java
- src/main/java/io/th0rgal/oraxen/utils/limitedplacing/LimitedPlacing.java
> Minor fixes and improvements

- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/furniture/FurnitureListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/noteblock/NoteBlockMechanicListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/stringblock/StringBlockMechanicListener.java
> Fix placing against CB

- src/main/java/io/th0rgal/oraxen/compatibilities/CompatibilitiesManager.java
- src/main/java/io/th0rgal/oraxen/compatibilities/provided/worldedit/WorldEditListener.java
- src/main/java/io/th0rgal/oraxen/compatibilities/provided/worldedit/WorldEditUtils.java
- src/main/java/io/th0rgal/oraxen/compatibilities/provided/worldedit/WrappedWorldEdit.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/noteblock/NoteBlockMechanic.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/noteblock/NoteBlockMechanicListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/stringblock/StringBlockMechanic.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/stringblock/StringBlockMechanicListener.java
> Worldedit Support

- src/main/java/io/th0rgal/oraxen/compatibilities/provided/worldedit/WorldEditListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/stringblock/StringBlockMechanic.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/stringblock/StringBlockMechanicListener.java
> add "tall" property to stringblock

- src/main/java/io/th0rgal/oraxen/OraxenPlugin.java
- src/main/java/io/th0rgal/oraxen/config/Settings.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/farming/smelting/SmeltingMechanicListener.java
- src/main/java/io/th0rgal/oraxen/utils/AdventureUtils.java
- src/main/java/io/th0rgal/oraxen/utils/customarmor/CustomArmorListener.java
- src/main/resources/settings.yml
> Minor bugfixes and features

- build.gradle
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/furniture/FurnitureMechanic.java
- src/main/resources/plugin.yml
Currently spawns an armor stand to use as the base entity
Try and just use the itemframe that holds the mechanic etc, and fix rotation just on the modelentity not the itemframe
> Modelengine Furniture

- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/furniture/FurnitureListener.java
> fix explosive arrows bypassing protection checks

- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/furniture/FurnitureListener.java
> fix projectile bypass

- src/main/java/io/th0rgal/oraxen/compatibilities/provided/worldedit/WorldEditHandlers.java
- src/main/java/io/th0rgal/oraxen/compatibilities/provided/worldedit/WorldEditListener.java
- src/main/java/io/th0rgal/oraxen/compatibilities/provided/worldedit/WrappedWorldEdit.java
> fix eventhandler on spigot servers

- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/noteblock/NoteBlockMechanicFactory.java
> fix directional rotations in blockstate file

- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/furniture/FurnitureListener.java
> move non-hitbox furniture projectile check into entitydamageevent

- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/furniture/FurnitureListener.java
> properly remove furniture on event cancellation

- src/main/java/io/th0rgal/oraxen/config/Settings.java
- src/main/java/io/th0rgal/oraxen/utils/CustomArmorsTextures.java
- src/main/resources/settings.yml
currently doubles animated image for some reason
but seems to mostly work ingame
Optifine system not working at all
> work on animated armor

- build.gradle
- remove not working & useless repos
- change out command API version
> fix build.gradle

- src/main/java/io/th0rgal/oraxen/pack/generation/AtlasGenerator.java
make atlas generation use only sprites, to filter out any non item texxtures
> Fix mip level error in atlas file

- src/main/java/io/th0rgal/oraxen/api/OraxenBlocks.java
- src/main/java/io/th0rgal/oraxen/api/OraxenFurniture.java
- src/main/java/io/th0rgal/oraxen/api/events/OraxenFurnitureInteractEvent.java
- src/main/java/io/th0rgal/oraxen/api/events/OraxenFurniturePlaceEvent.java
- src/main/java/io/th0rgal/oraxen/api/events/OraxenNoteBlockInteractEvent.java
- src/main/java/io/th0rgal/oraxen/api/events/OraxenNoteBlockPlaceEvent.java
- src/main/java/io/th0rgal/oraxen/api/events/OraxenStringBlockInteractEvent.java
- src/main/java/io/th0rgal/oraxen/api/events/OraxenStringBlockPlaceEvent.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/furniture/FurnitureListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/noteblock/NoteBlockMechanicListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/stringblock/StringBlockMechanicListener.java
New param for OraxenFurniturePlaceEvent to get the item with which the user placed the furniture.
> add itemInHand param to all OraxenPlaceEvents

- gradle.properties
- src/main/java/io/th0rgal/oraxen/font/FontEvents.java
- src/main/java/io/th0rgal/oraxen/items/ItemParser.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/noteblock/NoteBlockMechanicListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/noteblock/NoteBlockSoundListener.java
- src/main/java/io/th0rgal/oraxen/utils/BlockHelpers.java
- src/main/java/io/th0rgal/oraxen/utils/armorequipevent/ArmorListener.java
- src/main/java/io/th0rgal/oraxen/utils/inventories/ItemsView.java
- src/main/resources/items/armors.yml
- src/main/resources/items/hats.yml
- src/main/resources/items/items.yml
- src/main/resources/items/weapons.yml
```yml
- Fix anvil renaming of Oraxen Items
- Fix enchanting Oraxen Items making name italic
- Remove spam of NumberKey debug message
- Fix Written Books opening when trying to interact with blocks like Lecterns, Chiseled Bookshelves and chests
- Remove need to specify UUID and name in AttributeModifiers
- Fix issue related to sounds when placing on Custom Blocks
- Minor fixes to OraxenEvent calling
- Fix issues with assigning slots in OraxenInventory
```
> release: 1.157.4

- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/furniture/FurnitureMechanic.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/noteblock/NoteBlockMechanic.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/stringblock/StringBlockMechanic.java
- src/main/java/io/th0rgal/oraxen/utils/drops/Drop.java
Fixes:
- generating items with furniture or noteblock mechanic when stringblock mechanic is disabled
- generating items with noteblock mechanic when drops section is null
> Fix generating items with disabled stringblock mechanic and more

- core/src/main/java/io/th0rgal/oraxen/config/Settings.java
- core/src/main/java/io/th0rgal/oraxen/pack/upload/hosts/Polymath.java
- core/src/main/resources/settings.yml
- Made Polymath id a config variable in settings.yml so self hosted polymath instances can limit resource pack uploads from unknown sources
> Resource pack upload improvements

- core/src/main/java/io/th0rgal/oraxen/pack/dispatch/BukkitPackSender.java
**[Fixes]**
- fix resource pack being sent multiple times
> fix resource pack being sent multiple times

- README.md
> fix <dependency> end tag in readme.md

- core/src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/furniture/FurnitureSoundListener.java
- core/src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/noteblock/NoteBlockSoundListener.java
- core/src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/stringblock/StringBlockSoundListener.java
- core/src/main/java/io/th0rgal/oraxen/utils/BlockHelpers.java
Should fixed:
https://github.com/oraxen/oraxen/issues/1195
https://github.com/oraxen/oraxen/issues/1196
> fix: stone step sound will play when walking at the edge of block and stone break sound doesn't play for vanilla blocks

- core/src/main/java/io/th0rgal/oraxen/items/ItemParser.java
- core/src/main/java/io/th0rgal/oraxen/utils/BlockHelpers.java
- core/src/main/java/io/th0rgal/oraxen/utils/inventories/ItemsView.java
- core/src/main/resources/settings.yml
1. Improve isStandingInside checks (Use the correct collision box to determine whether the entity is standing at the target position of the block)
2. Support custom oraxen inventory icon display name
> New features and improvements

- core/src/main/java/io/th0rgal/oraxen/utils/BlockHelpers.java
- core/src/main/resources/settings.yml
> fix: correct the oraxen inventory items display name to Items

- core/src/main/java/io/th0rgal/oraxen/api/OraxenFurniture.java
Fix: 
https://github.com/oraxen/oraxen/issues/1264
> Check location has furniture entity

- core/src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/furniture/FurnitureSoundListener.java
Placing vanilla string blocks wont play a place sound, this PR fixes that.
> vanilla string placement sound fix

- core/src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/noteblock/NoteBlockMechanicListener.java
- v1_18_R1/src/main/java/io/th0rgal/oraxen/nms/v1_18_R1/NMSHandler.java
- v1_18_R2/src/main/java/io/th0rgal/oraxen/nms/v1_18_R2/NMSHandler.java
- v1_19_R1/src/main/java/io/th0rgal/oraxen/nms/v1_19_R1/NMSHandler.java
- v1_19_R2/src/main/java/io.th0rgal.oraxen.nms.v1_19_R2/NMSHandler.java
- v1_19_R3/src/main/java/io.th0rgal.oraxen.nms.v1_19_R3/NMSHandler.java
- v1_20_R1/src/main/java/io/th0rgal/oraxen/nms/v1_20_R1/NMSHandler.java
- v1_20_R2/src/main/java/io/th0rgal/oraxen/nms/v1_20_R2/NMSHandler.java
- v1_20_R3/src/main/java/io/th0rgal/oraxen/nms/v1_20_R3/NMSHandler.java
Fix not being able to add more pink petals/sea pickles
Fix waterloggable blocks not being able to be waterlogged when interacting block with water bucket
Fix items like paintings and fireworks not being used when right clicking Custom Block
> Fix interaction with Custom Blocks and Items + Block Placement Corrections

- core/src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/custom_block/noteblock/NoteBlockMechanicListener.java
this should also fix arm swing animation swinging the offhand when placing oraxen block against oraxen block while sneaking
> fix: arm swing animation when placing against replaceable block

- v1_20_R4/src/main/java/io/th0rgal/oraxen/nms/v1_20_R4/NMSHandler.java
> Make 1.20.5 nms.

- core/src/main/resources/languages/korean.yml
Fix korean typo in korean lang file (@짱구, @Shihyeon)
> fix: korean typo in korean lang file

- core/src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/custom_block/noteblock/NoteBlockMechanicInstrumentListener.java
- core/src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/custom_block/noteblock/RegularNoteBlock.java
> fix: noteblock particle location in wrong y level, also fix isSneakingWithHandOccupied if statement

- core/src/main/resources/languages/pt-BR.yml
* Update various messages in the pt-BR.yml file;
* Fix typos and improve wording for better clarity;
* Add missing translations for the new features and commands;
Let me know if there's anything else you'd like me to adjust!
> Update pt-BR language file

- build.gradle.kts
- core/src/main/java/io/th0rgal/oraxen/font/ShiftTag.java
- core/src/main/java/io/th0rgal/oraxen/nms/GlyphHandlers.java
- v1_20_R3/build.gradle.kts
- v1_20_R4/build.gradle.kts
- v1_21_R1/build.gradle.kts
- Component#replaceText is a replacement of ALL matched content if any condition is not provided.
- TextComponent#content is a just a single string in single component; you have to use PlainTextComponentSerializer.
- TextReplacementConfig supports result-based replacement.
> Fix GlyphHandlers#transformGlyphs

- core/src/main/java/io/th0rgal/oraxen/pack/generation/PredicatesGenerator.java
- gradle.properties
closes https://github.com/oraxen/oraxen/issues/1606
> fix: resourcepack generation in sub 1.21.4 mc versions

- core/src/main/java/io/th0rgal/oraxen/utils/drops/Drop.java
Simply solved the NPE probels.
> fix(drops): Fixed the NPE issues when using Drop.emptyDrop.

- build.gradle.kts
- core/src/main/java/io/th0rgal/oraxen/utils/VersionUtil.java
This makes the plugin start on 1.21.8
> Make the plugin start on 1.21.8

- core/src/main/java/io/th0rgal/oraxen/items/ItemParser.java
Adds 'final' keyword to local variables and method parameters throughout ItemParser to enhance code readability and maintainability. Also refactors enchantment parsing for better compatibility with Minecraft versions 1.21 and above, and improves error handling and logging for invalid enchantment keys.
> Refactor enchantment parsing logic in ItemParser
