oraxen/oraxen

- src/main/java/io/th0rgal/oraxen/pack/upload/UploadManager.java
- src/main/java/io/th0rgal/oraxen/pack/upload/hosts/HostingProvider.java
- src/main/java/io/th0rgal/oraxen/pack/upload/hosts/TransferDotSh.java
- 🐛 Fix pack upload error message feature not working as expected and add some forgotten stuff at first (remove resource pack url if not uploaded for example)
> 🐛 Fix pack upload error message feature

- src/main/java/io/th0rgal/oraxen/utils/drops/Loot.java
Was having issues with loot on block drops. Usage should work following the format below.
```yaml
drop:
loots:
- {oraxen_item: caveblock, probability: 1.0, max_amount: 32}
- {minecraft_type: DIRT, probability: 1.0, max_amount: 64}
```
> Fixed Loots

- build.gradle
This change fixes issue #81 by adding the maven plugin to  build.gradle, so that the jar gets installed to the local repository and that jitpack can grab it.
> Add maven plugin to build.gradle

- src/main/java/io/th0rgal/oraxen/mechanics/provided/block/BlockMechanicFactory.java
- Regrouped common method scopes.
- Implemented two new methods /w documentation to enable the ability to update direct blocks with Oraxen item models and textures.
> New API Methods - BlockMechanicFactory

- src/main/java/io/th0rgal/oraxen/mechanics/provided/noteblock/NoteBlockMechanicFactory.java
A very minor mistake in the variable naming I spotted.
> fix naming of noteblock blockstate variable

- .github/dependabot.yml
- build.gradle
- jitpack.yml
- Removed github packages auth (you can put it back)
- Removed withJavadocJar (missing javadoc creates a lot of warnings, you can put it back / add the javadoc: I just don't like warnings)
- Added working jitpack.yml for java 16
> Fixed JitPack support

- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/repair/RepairMechanicListener.java
The division often resulted in value in range 0 to 1 and as it was done on ints, it was rounded down resulting in multiplication by 0 and there fore setting damage on Damageable to 0.
> Fix RepairMechanic setting wrong real durability on Damageable items

- src/main/resources/settings.yml
``/o pack get`` is no longer a valid command, replaced with ``/o pack send @p``
>  failed_download:content message updated

- src/main/resources/plugin.yml
Add NBTAPI to plugin.yml to stop this error:
`[io.th0rgal.oraxen.OraxenPlugin] [Oraxen] Oraxen | Loaded class de.tr7zw.nbtapi.NBTContainer from NBTAPI v2.8.0 which is not a depend, softdepend or loadbefore of this plugin.`
> add NBTAPI to plugin.yml

- build.gradle
If you don't set the classifier to null, "-all" will be added at the end of the jar's name so Maven't won't recognize it.
This causes that, even if JitPack shows the compilation was successful, Maven won't be able to load the dependency.
> Fixing Maven not being able to find jar

- src/main/java/io/th0rgal/oraxen/pack/generation/PredicatesGenerator.java
Currently, oraxen generates the JSON file for potions incorrectly:
```json
{
"parent": "item/generated",
"textures": {
"layer0": "item/potion",
"layer1": "item/potion_overlay"
}
}
```
It should generate like this:
```json
{
"parent": "item/generated",
"textures": {
"layer0": "item/potion_overlay",
"layer1": "item/potion"
}
}
```
This PR fixes it! 😄
> Fix potion generation

- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/furniture/FurnitureMechanic.java
Seems like stand could be removed. This commit will add a check if stand is null
```
[19:27:45 ERROR]: Could not pass event BlockBreakEvent to Oraxen v1.125.0
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Entity.getPassengers()" because "stand" is null
at io.th0rgal.oraxen.mechanics.provided.gameplay.furniture.FurnitureMechanic.removeSolid(FurnitureMechanic.java:257) ~[oraxen-1_125_0.jar:?]
at io.th0rgal.oraxen.mechanics.provided.gameplay.furniture.FurnitureListener.onFurnitureBreak(FurnitureListener.java:243) ~[oraxen-1_125_0.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor58.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
at …
```
> Added check if stand is null for seat removing (NullPointerException)

- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/block/BlockMechanicListener.java
Small fix which sends the arm animation to the player when placing a block which uses the mushroom stem mechanic.
> Send arm animation when placing custom blocks.

- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/stringblock/StringBlockMechanicListener.java
Fixes the error that is being thrown when breaking a note_block  - Casting it as tripwire
> Fix checking for wrong material

- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/noteblock/NoteBlockMechanicListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/stringblock/StringBlockMechanicListener.java
Closes #301 
Currently noteblocks will update their blockstate if pushed onto specific blocks. Tried cancelling this but couldnt get a reliable way.
Not to mention the block will simply drop a noteblock and loose all other behaviour.
Therefore I just set it to cancel them
For tripwires it would normally drop just a string, now it creates a drop from the tripwire
https://user-images.githubusercontent.com/62521371/161433615-a19436ca-4400-4330-8824-4d8738e97217.mp4
> "fix" piston interactions

- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/furniture/FurnitureListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/furniture/FurnitureMechanic.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/stringblock/StringBlockMechanicListener.java
Main feature is the addition of multiple seat support.
Currently it spawns a new saeat wherever the furniture has a barrierblock
Was unsure if it should be a separate map of BlockLocation or what. [Examples](https://discord.com/channels/480068531132563476/589036101411274765/964656568283045958)
If you want it changed I can do so
https://user-images.githubusercontent.com/62521371/163673368-488aac54-3c90-4633-ae2b-1349f532cced.mp4
Also fixes placing furniture on custom blocks
https://user-images.githubusercontent.com/62521371/163673371-59273c51-cc4c-4075-85bd-3279fbaafd9a.mp4
And Tripwire breaking bug.
https://user-images.githubusercontent.com/62521371/163673374-ba5250e6-a097-477f-ab3d-7434660d117a.mp4
> Multiple seating and custom block fixes

- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/furniture/FurnitureListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/furniture/FurnitureMechanic.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/noteblock/NoteBlockMechanicListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/stringblock/StringBlockMechanicListener.java
- src/main/java/io/th0rgal/oraxen/utils/drops/Drop.java
Closes #274 
Fixes #253 
**Fixes issue with projectiles destroying furniture items.**
Specifically checks ProjectileHitEvent as compared to EntityDamageByEntity event it cancels collision not damage, thus you can pick up the arrow again, like normal vanilla interaction
https://user-images.githubusercontent.com/62521371/163677912-f7db628c-d6b2-49aa-b6fa-a4ce30897ed7.mp4
**Fixes explosions dropping non-custom variant of a block.** 
Bases the drop as if player broke it with their hand, meaning ores will not drop
https://user-images.githubusercontent.com/62521371/163712398-5aac3ed9-bb0e-4bd7-887a-f11c8ee38f08.mp4
**Fixed recently found bug when breaking dyed furniture.**
Now it will drop the actual color that was on said furniture, and not base it on the config version of the item. …
> fix various unintended custom block bugs

- build.gradle
- src/main/java/io/th0rgal/oraxen/mechanics/MechanicsManager.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/farming/watering/WateringMechanic.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/farming/watering/WateringMechanicFactory.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/farming/watering/WateringMechanicListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/furniture/FurnitureListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/furniture/FurnitureMechanic.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/furniture/evolution/EvolutionTask.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/noteblock/NoteBlockMechanic.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/noteblock/NoteBlockMechanicFactory.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/noteblock/NoteBlockMechanicListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/noteblock/farmblock/FarmBlockDryout.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/noteblock/farmblock/FarmBlockTask.java
- src/main/resources/mechanics.yml
Adds a "Farm Block" block. Essentially farmland for custom blocks, but will eventually have more interactions.
Includes mechanic for watering can aswell, tho I plan on merging all this into a Farming mechanic by the end of the PR.
Not sure on how it should split the "isFarmBlock" mechanic as they do kinda only exist for noteblocks, tho they could in theory be furniture aswell. thoughts?
First mechanic i add so it probably is badly formatted so please correct anything.
> More farming mechanics

- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/noteblock/NoteBlockMechanicFactory.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/noteblock/logstrip/LogStripListener.java
Also lets you specify a different strippedBlock on subblocks, otherwise it fetches the parents version
https://user-images.githubusercontent.com/62521371/172019031-d02bcd34-ffbf-4182-b12a-cc9aefcf0f91.mp4
> Fix logstripping for directional blocks

- src/main/java/io/th0rgal/oraxen/pack/dispatch/AdvancedPackSender.java
- src/main/java/io/th0rgal/oraxen/pack/dispatch/BukkitPackSender.java
- src/main/java/io/th0rgal/oraxen/pack/upload/UploadManager.java
Made some changes that fix the problem with the pack being loaded multiple times when a player joins the server.
Made the reload command to be able to un-register the join event if the user decides to disable both the send-pack and send-join-message options.
> Pack sender related fixes and changes.

- src/main/java/io/th0rgal/oraxen/commands/CommandsManager.java
- src/main/java/io/th0rgal/oraxen/commands/GlyphCommand.java
- src/main/java/io/th0rgal/oraxen/commands/ReloadCommand.java
- src/main/java/io/th0rgal/oraxen/font/FontEvents.java
- src/main/java/io/th0rgal/oraxen/font/FontManager.java
- src/main/java/io/th0rgal/oraxen/font/Glyph.java
To my knowledge this is the best we could do.
It is rather annoying that it requires a fake player that cant be removed from the tablist but
Added option to let people specify the playericon it should use to help abit
Config example:
```yml
heart:
texture: default/chat/heart
ascent: 8
height: 8
chat:
tabcomplete: true
tabIcon: c6307390-acda-48f8-8584-42087ad918f4
placeholders:
- "<3"
permission: "oraxen.emoji.heart"
> emote tabcompletion support

- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/furniture/FurnitureListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/furniture/FurnitureMechanic.java
- src/main/java/io/th0rgal/oraxen/pack/upload/UploadManager.java
This PR fixes one error produced by the oraxen pack command if someone had both the send_pack and the send_join_message options set to false. The PR  also fixes two problems with the sitting ability of the furniture mechanic. The first problem is the rotation of the player when they are sitting on furniture, and the second problem is the ability of the player to seat on furniture if another player was sitting there and then left the server.
For the first problem, I kept the ability for someone to set the yaw of the seat manually through the config like this:
```
seat:
height: 0
yaw: 0
```
But now you can just remove the yaw option and the plugin will set the yaw based on the rotation of the furniture. Example:
```
seat:
height: 0
```
For the second problem, I added a PlayerQuitListener …
> Fixed an error related to the oraxen pack command and also fixed two issues with the sitting ability of the furniture mechanic.

- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/noteblock/NoteBlockMechanicFactory.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/stringblock/StringBlockMechanicFactory.java
Idea is that they wont run unless theres an item configured with it
Could simply add more options in mechanics.yml but this feels abit more dynamic and more supporting of backwards compat
not the prettiest but easiest way i could find to loop through itemconfigs and look for mechanic X
> add check for schedulers

- build.gradle
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/block/BlockMechanicListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/noteblock/NoteBlockMechanicListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/stringblock/StringBlockMechanicListener.java
- src/main/java/io/th0rgal/oraxen/utils/BlockHelpers.java
Updated mcv 1.19:
> Only updated the version in build.gradle
Fixed server crash:
> In Paper 1.19 build 62 - 66 (possibly more) the Server crashes when e.g. Location.getChunk() or similar Chunk related methods are called if the given Chunk does not yet exist.
-> Added isLoaded() method to BlockHelper
-> Added isLoaded() call to all GenericGameEvent methods that seem to be able to crash the Server (Provide not existent Chunk data).
Side-note: All 'missing' Chunks seem to be in the nether.
> Update mcv to 1.19 & Fixed server crash

- src/main/java/io/th0rgal/oraxen/OraxenPlugin.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/furniture/FurnitureListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/noteblock/NoteBlockMechanicListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/stringblock/StringBlockMechanicListener.java
This PR fixes an error that could happen if someone was in creative mode and was moving a barrier block in their inventory while targeting a furniture block from 6+ blocks afar(This is also present to the string mechanic and noteblock mechanic). [furniture mechanic error](https://youtu.be/HRG7y83hK3s), [string mechanic error](https://youtu.be/hUA4caWPhE4), [noteblock mechanic error](https://youtu.be/I9MtJmJWp9A)
This PR also fixes an issue with the furniture mechanic not clearing the added block data. This could result in the following [problem](https://youtu.be/2P2dMWjeqs8) when you were middle-clicking a barrier block that was added at a location where previously was a furniture block.
> Fixes for the furniture, string and noteblock mechanics.

- src/main/java/io/th0rgal/oraxen/commands/CommandsManager.java
- src/main/java/io/th0rgal/oraxen/commands/GlyphCommand.java
- src/main/java/io/th0rgal/oraxen/config/Message.java
- src/main/java/io/th0rgal/oraxen/font/FontManager.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/farming/harvesting/HarvestingMechanicManager.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/furniture/FurnitureListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/noteblock/NoteBlockMechanicFactory.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/stringblock/StringBlockMechanicFactory.java
- src/main/java/io/th0rgal/oraxen/sound/CustomSound.java
- src/main/java/io/th0rgal/oraxen/sound/SoundManager.java
- src/main/resources/languages/czech.yml
- src/main/resources/languages/english.yml
- src/main/resources/languages/french.yml
- src/main/resources/languages/german.yml
- src/main/resources/languages/zh-CN.yml
- src/main/resources/languages/zh-TW.yml
- src/main/resources/settings.yml
Some old sounds didnt work as forgot to change `sound` to `sounds`.
This adds option to either specify 1 sound with `sound` or a list with `sounds`.
Also fixes some issues with CB sounds
Adds option to emoji list (now `/oraxen emoji`) to display all emojis, not on permission basis via settings.yml (adds hovermsg to showcase those you dont have perm for)
add check for shifts.yml to prevent console warning (harmless but annoying)
update MiniMessage parse method as scheduled to be removed someday
Fix bug with non-barrier furniture dropping dyed furniture incorrectly
> Minor features and bugfixes

- build.gradle
Bumped the version of CommandAPI to fix the startup issue on 1.19.1 servers.
closes #433
> Fixes the 1.19.1 startup issue.

- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/block/BlockMechanic.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/block/BlockMechanicListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/furniture/FurnitureListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/furniture/FurnitureMechanic.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/noteblock/NoteBlockMechanic.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/stringblock/StringBlockMechanic.java
- src/main/java/io/th0rgal/oraxen/utils/breaker/BreakerSystem.java
- src/main/resources/sound.yml
This adds new entries to sound.yml for  `block.stone.x` same as for noteblocks as barriers inherit stone sound.
Also makes it so if a config entry wants to use `block.stone.x` it is repathed to the custom version automatically
> add sounds to furniture

- build.gradle
This should fix the startup error that CommandAPI does not support the server version when loading the plugin on 1.19.2.
> Fix 1.19.2 Startup Issue

- src/main/java/io/th0rgal/oraxen/commands/ItemInfoCommand.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/block/BlockMechanic.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/block/BlockMechanicFactory.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/block/BlockMechanicListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/furniture/FurnitureListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/noteblock/NoteBlockMechanic.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/noteblock/NoteBlockMechanicListener.java
- src/main/java/io/th0rgal/oraxen/utils/breaker/BreakerSystem.java
Fixes issue with stone/stone-like blocks missing sounds
Adds a `can_ignite` property to noteblock/block mechanic to say if flint&steel/lava etc can ignite them, default to false
> Minor features & Bugfixes

- src/main/java/io/th0rgal/oraxen/config/ConfigsManager.java
- src/main/java/io/th0rgal/oraxen/font/FontEvents.java
- src/main/java/io/th0rgal/oraxen/font/Glyph.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/block/BlockMechanic.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/block/BlockMechanicFactory.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/block/BlockMechanicListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/furniture/FurnitureListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/furniture/FurnitureMechanic.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/noteblock/NoteBlockMechanic.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/noteblock/NoteBlockMechanicListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/stringblock/StringBlockMechanicListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/stringblock/sapling/SaplingListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/misc/custom/listeners/BreakListener.java
- src/main/java/io/th0rgal/oraxen/utils/BlockHelpers.java
- src/main/java/io/th0rgal/oraxen/utils/breaker/BreakerSystem.java
- src/main/java/io/th0rgal/oraxen/utils/drops/Loot.java
- src/main/resources/items/armors.yml
Fixes some sound-related nullpointers
Tweak playEffect for sapling mechanic
Make Drop/Loot mechanic support `crucible_item` as item option
Validate all glyphs and find which ones are misconfigured, also replaces to prevent entire font from breaking, Closes #394 
Automatically translate glyphs on signs and books and color correct
https://user-images.githubusercontent.com/62521371/185723430-aab3a7d3-4e13-4007-992d-b10663c25eb3.mp4
Add ItemBreak as CustomListener, Closes #257
> More Bugfixes

- src/main/java/io/th0rgal/oraxen/compatibilities/provided/placeholderapi/OraxenExpansion.java
`[01:35:08 INFO]: [PlaceholderAPI] Successfully registered expansion: oraxen [${projectVersion}]`
i fixed that)
> Fix plugin version in PAPI Expansion

- src/main/java/io/th0rgal/oraxen/config/Settings.java
- src/main/java/io/th0rgal/oraxen/items/ModelData.java
- src/main/resources/settings.yml
Closes #451 
Settings.yml example
```yml
automatically_set_model_data: true
skipped_model_data_numbers: # list of model data numbers the automatic system will skip
- 1-4
- 10-12
- 7-9
```
> add option to blacklist cmd values

- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/durability/DurabilityMechanicManager.java
Since the plugin may handle the durability of some items, we have to update the event accordingly when we do so.
changeDurability method now returns if we have made any modification to the item.
When it returns true, we set the damage or repair amount to 0 so we don't break or repair an item.
This is needed because we need to know if we have handled the durability ourselves or not before modifying the event.
This fixes armours breaking when they shouldn't and items with mending displaying incorrect damage after being repaired.
> Fixed armors breaking when they shouldn't

- src/main/java/io/th0rgal/oraxen/OraxenPlugin.java
I had the problem that the plugins throws a NullPointer when using the plugin on ArchLinux.
This simple PR fixes this problem
> Ignore os being null on startup

- src/main/java/io/th0rgal/oraxen/commands/PrintGlyphCommand.java
Missing a `.collect()` call on the Stream to get all mapped values.
I don't know if you want to keep the value `all` as first or not, but we can also instanciate one List by doing this:
```java
final List<String> glyphnames = glyphnames.addAll(OraxenPlugin.get().getFontManager().getGlyphs().stream().map(Glyph::getName).collect(Collectors.toList()));
glyphnames.add("all");
```
> fix function `getPrintGlyphCommand`

- src/main/java/io/th0rgal/oraxen/items/OraxenMeta.java
- src/main/java/io/th0rgal/oraxen/pack/generation/ModelGenerator.java
This PR adds a better texture system with support to the old one (so it's optional).
The advantage of this system is that it allows you to use any parent model template (so if you create custom model and you want it to work as template like `block/cube_all` etc., this system allows you to to that!)
Examples:
```yaml
Pack:
generate_model: true
parent_model: block/cube
textures:
particle: block/texture_north
down: block/texture_down
up: block/texture_up
north: block/texture_north
south: block/texture_south
west: block/texture_west
east: block/texture_east
```
```yaml
Pack:
generate_model: true
parent_model: block/cube_bottom_top
textures:
top: block/texture_top
side: block/texture_side
bottom: block/texture_bottom
```
> Add better texture system

- src/main/java/io/th0rgal/oraxen/api/events/OraxenNoteBlockInteractEvent.java
- src/main/java/io/th0rgal/oraxen/api/events/OraxenStringBlockInteractEvent.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/noteblock/NoteBlockMechanicListener.java
- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/stringblock/StringBlockMechanicListener.java
Interact event would be triggered twice because players have two hands. Added equipmentslot params for developers to get the hand
> Improve interact event

- src/main/java/io/th0rgal/oraxen/OraxenPlugin.java
- src/main/java/io/th0rgal/oraxen/font/FontManager.java
Adds new glyph tab completion system using 1.19.1 custom chat completion packet, should work on lower versions using old code.
Also fixes null protocolManager field in FontManager and removes double initialization of CommandManager and FontManager.
> Add new glyph tab completion

- src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/noteblock/NoteBlockMechanicFactory.java
Two issues here - order of operations was incorrect with mod + div
And a 386 was used instead of a 400 - 400 is what should be used as 26 was already added to the ID before being passed to that method
> Fix incorrect logic for dealing with high IDs in note block mechanic

- src/main/java/io/th0rgal/oraxen/pack/generation/DuplicationHandler.java
This covers a bug which I was made aware of when working with Oraxen, where duplicated files could not be migrated on Linux-based systems (e.g.):
```
[17:46:20] [Server thread/INFO]: Oraxen | Successfully updated settings.yml
[17:46:21] [Server thread/INFO]: Oraxen | Generating atlas-file for 1.19.3 Resource Pack format
[17:46:21] [Server thread/INFO]: Oraxen | Duplicate file detected: assets/minecraft/models/item/leather_horse_armor.json - Attempting to migrate it
[17:46:21] [Server thread/INFO]: Oraxen | Found a duplicate leather_horse_armor.json, attempting to migrate it into Oraxen item configs
[17:46:21] [Server thread/INFO]: Oraxen | Failed to migrate duplicate file-entry, could not read file
```
With the main culprit being shared host services.
This PR removes the use of …
> fix: duplicate file entries not reading on linux

- src/main/java/io/th0rgal/oraxen/font/FontEvents.java
When I send a glyph placeholder on the chat, it gets replaced to an empty char
> Fix glyphs placeholders not showing on chat

- src/main/java/io/th0rgal/oraxen/api/events/OraxenPackGenerateEvent.java
- src/main/java/io/th0rgal/oraxen/pack/generation/ResourcePack.java
Adds OraxenPackGenerateEvent - allows plugins to correctly use methods like `Resourcepack#writeStringToVirtual` (which wasn't possible before because of clearing output files when generating pack)
> Add OraxenPackGenerateEvent

- src/main/java/io/th0rgal/oraxen/mechanics/provided/combat/spell/thor/ThorMechanicListener.java
This is the same as #1029, but I closed that one by mistake when changing my default branch name hehe.
Almost same explanation as before...
Repeated part:
> Instead of checking the protection for the block the player interacts with, I changed it to check for the block where the lightning is going to be summoned on. With a 50 blocks range, the interacted block tends to be a "safe" block even when pointing into a protected area where the player is not supposed to be summoning anything.
New info:
Due to how lightning mechanic works (affecting/burning entities such as villagers or pets away from the strike zone), it might be good to consider a 3x3 or 5x5 area check, but I decided to leave that to your opinion whether to do it that way or not.
> Change checked protection for Thor Mechanic

- core/src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/durability/DurabilityMechanic.java
- core/src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/durability/DurabilityMechanicManager.java
After manually changing the durability of items with the durability mechanic, the event should be cancelled/set to 0.
> Fixed custom armors breaking too easily

- build.gradle.kts
- This updates the adventure dependencies for adventure to better support 1.20.4. For example, titles from adventure do not work on 1.20.4 without the dependency updates.
> Update adventure dependencies

- core/src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/stringblock/StringBlockMechanicListener.java
Before if you try to put a custom stringblock on where you're standing it wouldn't let you because there was a isStandingInside block check, it doesn't need a check for that if the stringblock is a block you can walk through
> Remove is standing inside check for Stringblock placement

- core/src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/furniture/FurnitureMechanic.java
If the entity hitbox not overrided, the entity will be judged as blocked, so the model will be skip render by the Network-Optimization options of ModelEngine.
> fix: fix ModelEngine model not render

- core/src/main/java/io/th0rgal/oraxen/pack/generation/DuplicationHandler.java
Migrated items sharing the same material, file name, and different paths were being overridden.
> fix: missing migrated items due to same model name

- core/src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/furniture/FurnitureSoundListener.java
If you break a block and said block was inside a furniture it won't play any block break sound, this PR fixes that.
> Fix sound for when a block is inside a furniture and you break it

- core/src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/noteblock/NoteBlockSoundListener.java
it would only run the wood hit sound if it was a noteblock or mushroom stem because I forgot to move the curly braces before when I was dealing with a conflict
> fix wood hit sound again (forgot to move curly braces)

- core/src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/furniture/FurnitureSoundListener.java
When breaking a custom string block it would always play a stone break sound, this PR fixes that.
> Fix stone block sound playing when breaking custom string block

- core/src/main/java/io/th0rgal/oraxen/api/OraxenBlocks.java
Fixes "java.lang.IllegalArgumentException: Wrong kind of data for this effect!" error for 1.19 servers, even though the data field is annotated as nullable it will still throw that error
> call World#playEffect on block break only if server is 1.20 or above

- core/src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/stringblock/StringBlockMechanicListener.java
if a stringblock is tall and you either cancel BlockPlaceEvent or OraxenStringBlockPlaceEvent, the string block above the target block will still be kept there, this pr fixes that issue
> Fix OraxenStringBlockPlaceEvent not cancelling properly for tall stringblocks

- core/src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/custom_block/CustomBlockHelpers.java
attempting to place custom block while the player is standing inside the tall block would actually break the tall block below and keep the other half of the tall block flying on the air, made a fix for it here
> fix: tall blocks breaking when attempting to place custom block while inside tall block

- core/src/main/java/io/th0rgal/oraxen/commands/CommandsManager.java
The hex2Rgb method in the CommandsManager class has thrown an NumberFormatException before this change and caused an error while executing the command. This issue should be fixed with this commit.
**Example:** /oraxen dye cyan
**Exception thrown before:**
[21:48:00 INFO]: Splatcrafter issued server command: /oraxen dye cyan
[21:48:00 ERROR]: [CommandAPI] Unhandled exception executing '/oraxen dye cyan'
java.lang.NumberFormatException: For input string: "ya" under radix 16
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
at java.lang.Integer.parseInt(Integer.java:668) ~[?:?]
at java.lang.Integer.valueOf(Integer.java:973) ~[?:?]
at io.th0rgal.oraxen.commands.CommandsManager.hex2Rgb(CommandsManager.java:50) ~[oraxen-1.173.0.jar:?]
at …
> Add NumberFormatException to hex2Rgb method

- build.gradle.kts
- core/build.gradle.kts
Hi, i rewrite some build script for 1.20.6
- In manifest, you can nominate your NMS option by using paperweight-mappings-namespace.
- Bumps some version.
- Downloads protocollib to default.
Notice: In current paper build, this error will be happened.
```
java.lang.NoSuchFieldError: Class net.minecraft.server.MinecraftServer does not have member field 'net.minecraft.commands.Commands vanillaCommandDispatcher'
```
This is because of CommandAPI's issue.
> Edits some build script, adds paper remapping attribute to successfully remapping for 1.20.6

- core/src/main/java/io/th0rgal/oraxen/api/OraxenBlocks.java
- core/src/main/java/io/th0rgal/oraxen/api/events/custom_block/OraxenBlockDropLootEvent.java
- core/src/main/java/io/th0rgal/oraxen/api/events/custom_block/OraxenCustomBlockDropLootEvent.java
- core/src/main/java/io/th0rgal/oraxen/api/events/custom_block/noteblock/OraxenNoteBlockBreakEvent.java
- core/src/main/java/io/th0rgal/oraxen/api/events/custom_block/noteblock/OraxenNoteBlockDropLootEvent.java
- core/src/main/java/io/th0rgal/oraxen/api/events/custom_block/stringblock/OraxenStringBlockBreakEvent.java
- core/src/main/java/io/th0rgal/oraxen/api/events/custom_block/stringblock/OraxenStringBlockDropLootEvent.java
- core/src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/custom_block/stringblock/StringBlockMechanicPhysicsListener.java
- core/src/main/java/io/th0rgal/oraxen/utils/drops/Drop.java
- core/src/main/java/io/th0rgal/oraxen/utils/drops/DroppedLoot.java
- core/src/main/java/io/th0rgal/oraxen/utils/drops/Loot.java
This PR adds a new non-cancellable event named OraxenBlockDropLootEvent.  This event will be fired after the loot has been dropped from the custom block. It contains information about the triggered mechanic, vanilla Block and Player if applicable. Additionally it also has a List<DroppedLoot> which contains every loot that was dropped before with the dropped amounts.
This event will be useful for plugins that are trying to implement something like a Hypixel collections plugin or generally just for saving/monitoring stats. 
I haven't tested if this actually work in game, since I never used custom block mechanics in Oraxen, but I don't see any reason why wouldn't it work.
I also tried not to break existing APIs. Usually just the return types changed from void in the method signatures.
> OraxenBlockDropLootEvent for the new API

- core/src/main/java/io/th0rgal/oraxen/config/Message.java
- core/src/main/java/io/th0rgal/oraxen/items/ItemParser.java
- core/src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/furniture/jukebox/JukeboxBlock.java
- core/src/main/java/io/th0rgal/oraxen/mechanics/provided/gameplay/furniture/jukebox/JukeboxListener.java
- core/src/main/java/io/th0rgal/oraxen/pack/generation/OraxenDatapack.java
- core/src/main/java/io/th0rgal/oraxen/pack/generation/ResourcePack.java
- core/src/main/java/io/th0rgal/oraxen/sound/CustomSound.java
- core/src/main/java/io/th0rgal/oraxen/sound/JukeboxDatapack.java
- core/src/main/java/io/th0rgal/oraxen/sound/SoundManager.java
- core/src/main/java/io/th0rgal/oraxen/utils/ItemUtils.java
- core/src/main/java/io/th0rgal/oraxen/utils/customarmor/TrimArmorDatapack.java
- core/src/main/resources/items/furniture.yml
- core/src/main/resources/items/items.yml
- core/src/main/resources/languages/czech.yml
- core/src/main/resources/languages/english.yml
- core/src/main/resources/languages/french.yml
- core/src/main/resources/languages/german.yml
- core/src/main/resources/languages/jpn_JP.yml
- core/src/main/resources/languages/korean.yml
- core/src/main/resources/languages/ru-RU.yml
- core/src/main/resources/languages/zh-CN.yml
- core/src/main/resources/languages/zh-TW.yml
- core/src/main/resources/settings.yml
- core/src/main/resources/sound.yml
- gradle.properties
This update improves the Jukebox feature, focusing on sounds and making use of new components to add more flexibility and functionality.
- **Custom Disks and Music**: You can now create your own disks with your own music, and Oraxen will handle the datapack generation automatically. This makes it easier to add custom content without extra hassle.
- **Reworked Furniture Integration**: It's now possible to create furniture that works like a jukebox in 1.21.3, using custom disks or regular ones, but with your own design. These can even have custom models when the disk is running.
- **Updated Default Config**: The default config has been updated to show off these new features. A new **turntable** ("tourne disque") has been added, which opens itself and starts spinning the disk when you insert …
> 1.185.0 Jukebox Update

- core/src/main/java/io/th0rgal/oraxen/mechanics/provided/misc/misc/MiscMechanic.java
- core/src/main/java/io/th0rgal/oraxen/mechanics/provided/misc/misc/MiscMechanicFactory.java
When using the `misc:` mechanic with only specific properties (e.g., `allow_in_vanilla_recipes: false`), the plugin would incorrectly show deprecation warnings for other properties that weren't explicitly configured.
For example, adding just:
```yaml
misc:
allow_in_vanilla_recipes: false
```
Would trigger warnings like:
```
[18:19:09 INFO]: Oraxen | [ITEM] seems to be using burns_in_fire which is deprecated....
[18:19:09 INFO]: Oraxen | It is heavily advised to swap to the new fire_resistant-property on all 1.20.5+ servers
```
Even though `burns_in_fire`, `burns_in_lava` or `breaks_from_cactus` were never explicitly set in the item's configuration.
1. **Buggy condition in MiscMechanicFactory**: Line 26 had `!mechanic.burnsInLava() || !mechanic.burnsInLava()` - calling `burnsInLava()` …
> Fix misc mechanic false deprecation warnings for unconfigured properties
